### ISSUE TITLE
gem公開

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/scrapbox2markdown#4]
gemインストールすればコマンドとして使えるようにしたい

```
$ gem install scrapbox2markdown
$ scrapbox2markdown --input test.json --output path/to/output
```

**Comment by noriyotcp** [comment]
@takeyuweb 今気づいたのですが、`title`, `created`, `updated` はScrapboxのJSONのほうにあるので、yamlの埋め込みはマークダウンへの変換と同時にしてやらないと厳しい？

JSONでこうなってるので
```json
"pages": [
    {
      "title": "はじめに",
      "created": 1522332459,
      "updated": 1522332459,
      "lines": [
```

出力されるマークダウンファイルにて

```md
---
title: "README.md"
tags: 
created_at: 2018-07-05 10:54:27 +0900
updated_at: 2018-07-05 10:54:27 +0900
---

ここから本文
```

となるとタグはどうするんだということになりますが、オプションでカンマ区切りで指定するとか
`--tags some,thing,else`

でもこれだと出力されるファイル全てに同じタグが付きますけど・・・

**Comment by takeyuweb** [comment]
> yamlの埋め込みはマークダウンへの変換と同時にしてやらないと厳しい？

そうですね、チェック忘れてました。
マークダウンを作る時にYAML形式でうめこみましょう。

YAMLの書式については決まりがあるわけでないので、こっちで考えてやって、あとはインポートするときにうまいぐらいやってやーで良いと思います。
ただ、他に参考にできるMarkdownがあるなら、それになるべく寄せた方がインポートスクリプト書く人にたいして親切だと思うので、esaを参考にすればよいかと。

で、タグについてはScrapboxにはタグという概念がないので、`tags:` は取っちゃって良いと思います。
